### ISSUE TITLE
Broken menu navigation

### ISSUE THREAD

**Issue by OscarL** [HaikuArchives/KeyCursor#3]
It seems my fix for #1 has broken menus navigation :-(

When opening the "top menu" of an app by "clicking" on it (using KeyCursor, of course), the menu shows up, but immediately disappears after "moving the pointer" (by using the arrow keys).

On the other hand, after invoking "context/popup" menus (e.g.: Tracker's drill-down) via "right click" (SHIFT+Space with KeyCursor) it is possible to to navigate those with no issues.

I guess I'll need a test-app to log what a regular mouse does, and compare that to what KeyCursor is doing.

In the meantime... I'll put on hold the planed update to the HaikuPorts recipe for KeyCursor :-(

**Comment by humdingerb** [comment]
@OscarL , how do you feel about reverting the above mentioned lines and do a release?
It's only the double-click in Tracker, right? At least a double-space for a double-click seems to work in e.g. Genio. In Tracker, it's OK to select with space and then open with RETURN, I guess.

Maybe @jscipione has an idea what's going on here. Him being a Tracker and BMenu specialist... :)

**Comment by humdingerb** [comment]
Alright. I reverted that part and will upload the catkeys to Polyglot for translation. Then do a release in a week or so.
If a fix for #1 presents itself until then, fine. But Iwouldn't know where to look... :)
